# Табличные данные

**Цель**:

**Требования к отчету (реализовано):**

In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('data/covtype.csv') # default delimiter is ','
df.head() # default is 5

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5

In [7]:
print(df.shape)

(581012, 55)

In [8]:
print(df.dtypes)

Elevation                             int64
Aspect                                int64
Slope                                 int64
Horizontal_Distance_To_Hydrology      int64
Vertical_Distance_To_Hydrology        int64
Horizontal_Distance_To_Roadways       int64
Hillshade_9am                         int64
Hillshade_Noon                        int64
Hillshade_3pm                         int64
Horizontal_Distance_To_Fire_Points    int64
Wilderness_Area1                      int64
Wilderness_Area2                      int64
Wilderness_Area3                      int64
Wilderness_Area4                      int64
Soil_Type1                            int64
Soil_Type2                            int64
Soil_Type3                            int64
Soil_Type4                            int64
Soil_Type5                            int64
Soil_Type6                            int64
Soil_Type7                            int64
Soil_Type8                            int64
Soil_Type9                            int64
Soil_Type10                           int64
Soil_Type11                           int64
Soil_Type12                           int64
Soil_Type13                           int64
Soil_Type14                           int64
Soil_Type15                           int64
Soil_Type16                           int64
Soil_Type17                           int64
Soil_Type18                           int64
Soil_Type19                           int64
Soil_Type20                           int64
Soil_Type21                           int64
Soil_Type22                           int64
Soil_Type23                           int64
Soil_Type24                           int64
Soil_Type25                           int64
Soil_Type26                           int64
Soil_Type27                           int64
Soil_Type28                           int64
Soil_Type29                           int64
Soil_Type30                           int64
Soil_Type31                           int64
Soil_Type32                           int64
Soil_Type33                           int64
Soil_Type34                           int64
Soil_Type35                           int64
Soil_Type36                           int64
Soil_Type37                           int64
Soil_Type38                           int64
Soil_Type39                           int64
Soil_Type40                           int64
Cover_Type                            int64
dtype: object

In [12]:
print(type(df.values)) # ? вывод типов данных;

<class 'numpy.ndarray'>

In [13]:
# TODO: какие столбцы являются числовыми, а какие категориальными.

In [22]:
print(f'Max:\n{df.max()}')
print(f'Min:\n{df.min()}')

Max:
Elevation                             3858
Aspect                                 360
Slope                                   66
Horizontal_Distance_To_Hydrology      1397
Vertical_Distance_To_Hydrology         601
Horizontal_Distance_To_Roadways       7117
Hillshade_9am                          254
Hillshade_Noon                         254
Hillshade_3pm                          254
Horizontal_Distance_To_Fire_Points    7173
Wilderness_Area1                         1
Wilderness_Area2                         1
Wilderness_Area3                         1
Wilderness_Area4                         1
Soil_Type1                               1
Soil_Type2                               1
Soil_Type3                               1
Soil_Type4                               1
Soil_Type5                               1
Soil_Type6                               1
Soil_Type7                               1
Soil_Type8                               1
Soil_Type9                               1
Soil_Type10                              1
Soil_Type11                              1
Soil_Type12                              1
Soil_Type13                              1
Soil_Type14                              1
Soil_Type15                              1
Soil_Type16                              1
Soil_Type17                              1
Soil_Type18                              1
Soil_Type19                              1
Soil_Type20                              1
Soil_Type21                              1
Soil_Type22                              1
Soil_Type23                              1
Soil_Type24                              1
Soil_Type25                              1
Soil_Type26                              1
Soil_Type27                              1
Soil_Type28                              1
Soil_Type29                              1
Soil_Type30                              1
Soil_Type31                              1
Soil_Type32                              1
Soil_Type33                              1
Soil_Type34                              1
Soil_Type35                              1
Soil_Type36                              1
Soil_Type37                              1
Soil_Type38                              1
Soil_Type39                              1
Soil_Type40                              1
Cover_Type                               7
dtype: int64
Min:
Elevation                             1859
Aspect                                   0
Slope                                    0
Horizontal_Distance_To_Hydrology         0
Vertical_Distance_To_Hydrology        -173
Horizontal_Distance_To_Roadways          0
Hillshade_9am                            0
Hillshade_Noon                           0
Hillshade_3pm                            0
Horizontal_Distance_To_Fire_Points       0
Wilderness_Area1                         0
Wilderness_Area2                         0
Wilderness_Area3                         0
Wilderness_Area4                         0
Soil_Type1                               0
Soil_Type2                               0
Soil_Type3                               0
Soil_Type4                               0
Soil_Type5                               0
Soil_Type6                               0
Soil_Type7                               0
Soil_Type8                               0
Soil_Type9                               0
Soil_Type10                              0
Soil_Type11                              0
Soil_Type12                              0
Soil_Type13                              0
Soil_Type14                              0
Soil_Type15                              0
Soil_Type16                              0
Soil_Type17                              0
Soil_Type18                              0
Soil_Type19                              0
Soil_Type20                              0
Soil_Type21                              0
Soil_Type22                              0
Soil_Type23                              0
Soil_Type24                              0
Soil_Type25                              0
Soil_Type26                              0
Soil_Type27                              0
Soil_Type28                              0
Soil_Type29                              0
Soil_Type30                              0
Soil_Type31                              0
Soil_Type32                              0
Soil_Type33                              0
Soil_Type34                              0
Soil_Type35                              0
Soil_Type36                              0
Soil_Type37                              0
Soil_Type38                              0
Soil_Type39                              0
Soil_Type40                              0
Cover_Type                               1
dtype: int64

In [24]:
print(f'Mean:\n{df.mean()}')

Mean:
Elevation                             2959.365301
Aspect                                 155.656807
Slope                                   14.103704
Horizontal_Distance_To_Hydrology       269.428217
Vertical_Distance_To_Hydrology          46.418855
Horizontal_Distance_To_Roadways       2350.146611
Hillshade_9am                          212.146049
Hillshade_Noon                         223.318716
Hillshade_3pm                          142.528263
Horizontal_Distance_To_Fire_Points    1980.291226
Wilderness_Area1                         0.448865
Wilderness_Area2                         0.051434
Wilderness_Area3                         0.436074
Wilderness_Area4                         0.063627
Soil_Type1                               0.005217
Soil_Type2                               0.012952
Soil_Type3                               0.008301
Soil_Type4                               0.021335
Soil_Type5                               0.002749
Soil_Type6                               0.011316
Soil_Type7                               0.000181
Soil_Type8                               0.000308
Soil_Type9                               0.001974
Soil_Type10                              0.056168
Soil_Type11                              0.021359
Soil_Type12                              0.051584
Soil_Type13                              0.030001
Soil_Type14                              0.001031
Soil_Type15                              0.000005
Soil_Type16                              0.004897
Soil_Type17                              0.005890
Soil_Type18                              0.003268
Soil_Type19                              0.006921
Soil_Type20                              0.015936
Soil_Type21                              0.001442
Soil_Type22                              0.057439
Soil_Type23                              0.099399
Soil_Type24                              0.036622
Soil_Type25                              0.000816
Soil_Type26                              0.004456
Soil_Type27                              0.001869
Soil_Type28                              0.001628
Soil_Type29                              0.198356
Soil_Type30                              0.051927
Soil_Type31                              0.044175
Soil_Type32                              0.090392
Soil_Type33                              0.077716
Soil_Type34                              0.002773
Soil_Type35                              0.003255
Soil_Type36                              0.000205
Soil_Type37                              0.000513
Soil_Type38                              0.026803
Soil_Type39                              0.023762
Soil_Type40                              0.015060
Cover_Type                               2.051471
dtype: float64

In [25]:
# TODO: признаки с наибольшим разбросом.

Выполните фильтрацию данных по одному условию (например, значение признака больше/меньше заданного).

In [32]:
CONDITION_NUMBER = 0.9
df_filtered = df[df['Soil_Type37'] > CONDITION_NUMBER]
df_filtered

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
6947,3333,22,15,85,-2,3684,210,208,131,2502,...,0,0,0,0,0,1,0,0,0,7
6948,3316,26,7,30,-3,3719,217,225,144,2391,...,0,0,0,0,0,1,0,0,0,7
6956,3405,75,31,108,13,3596,240,167,35,2714,...,0,0,0,0,0,1,0,0,0,7
6957,3359,47,20,150,4,3631,222,193,97,2574,...,0,0,0,0,0,1,0,0,0,7
6958,3320,16,12,0,0,3690,209,214,141,2379,...,0,0,0,0,0,1,0,0,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374215,3449,42,6,780,100,3429,221,227,142,1430,...,0,0,0,0,0,1,0,0,0,7
374216,3448,18,7,781,99,3421,215,226,148,1460,...,0,0,0,0,0,1,0,0,0,7
374846,3464,164,14,845,115,3494,232,243,139,1130,...,0,0,0,0,0,1,0,0,0,7
375498,3459,167,16,882,110,3476,231,244,140,1095,...,0,0,0,0,0,1,0,0,0,7
375499,3457,166,15,874,108,3466,231,244,140,1124,...,0,0,0,0,0,1,0,0,0,7